<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG7PXpiu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG7PXpiu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG7PXpiu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG7PXpiu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerG7PXpiu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'G7PXpiu',
    'container.build_id' => '40e70064',
    'container.build_time' => 1593472229,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG7PXpiu');
